applications:
  ll_project:
    type: python:3.12
    build:
      flavor: none

    dependencies:
      python:
        gunicorn: "*"
        psycopg2-binary: "*"
        platformshconfig: "*"

    web:
      commands:
        start: "gunicorn --bind 0.0.0.0:$PORT learning_log.wsgi:application"
      locations:
        "/":
          passthru: true
          allow: true
        "/static":
          root: "static"
          expires: 1h
          allow: true

    mounts:
      "/media":
        source: local
        source_path: media

    hooks:
      deploy: |
        python manage.py migrate --noinput
        python manage.py collectstatic --noinput --clear

    relationships:
      database: "db:postgresql"

services:
  db:
    type: postgresql:16
    size: S

routes:
  "https://{default}/":
    type: upstream
    upstream: "ll_project:http"
    cache:
      enabled: false

  "https://www.{default}/":
    type: redirect
    to: "https://{default}/"